qnow_site/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'qnow_site'

urlpatterns = [
    path('', views.site ,name='site'),
    path('accounts/login/', views.site ,name='site'), 
    path('contact/', views.contact ,name='contact'),
    path('about/', views.about ,name='about'),
    path('blog/', views.blog ,name='blog'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

""" 
O path accounts/login foi usado, para o acesso ao site principal e não a tela de login.
Isto porque, esta plataforma acessa dois tipos de login, o client e provider, para tal,
foram criadas rotas diferentes. Mas ao recuperar a senha, o link padrão, leva para o 
escrito acima e redirecionei ele para abrir o site 
"""

qnow_user/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView,LogoutView
from . import views


app_name = 'qnow_user'

urlpatterns = [
    path('login_client_start/', views.login_client_start, kwargs={'origin': 'client' }, name='login_client_start'),
    path('login_provider_start/', views.login_provider_start, kwargs={'origin': 'provider' }, name='login_provider_start'),
    
    path('login_client/',   LoginView.as_view(template_name='../templates/login.html',
                                     extra_context={'next':'qnow_client:quotation_client',
                                                    'origin':'client',
                                                    'active_page_client_provider':'active'
                                                    }
                                    ), name="login_client"),
    path('login_provider/', LoginView.as_view(template_name='../templates/login.html',
                                     extra_context={'next':'qnow_provider:quotation_provider',
                                                    'origin':'provider',
                                                    'active_page_client_provider':'active'
                                                    }
                                    ), name="login_provider"),

    path('logout/', LogoutView.as_view(template_name='../templates/index.html',
                                    extra_context={'next_page':'qnow_site:site',
                                                   'active_page_site': 'active',
                                    }),name='logout'),

    path('register_client/', views.register, kwargs={'origin': 'client' }, name='register_client'),
    path('register_provider/', views.register, kwargs={'origin': 'provider' }, name='register_provider'),

]

quotation-now/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
import re
from django.contrib.auth import urls,views


urlpatterns = [
    path('', include('qnow_site.urls',namespace='site')),
    path('admin/', admin.site.urls),
    path('accounts/', include('qnow_user.urls',namespace='accounts')),
    path('client/', include('qnow_client.urls',namespace='client')),
    path('provider/', include('qnow_provider.urls',namespace='provider')),
    path('', include('django.contrib.auth.urls')),
    ]

if settings.DEBUG:
    import debug_toolbar
    from django.urls import include
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls,namespace='debug')),
    ] + urlpatterns


#admin.site.site_header = 'Quotation-NOW'    
#admin.site.index_title = 'Q-NOW(Administrador)'    
#admin.site.site_title = 'Q-NOW'    

admin.site.site_header = 'MGA-Cotações'    
admin.site.index_title = 'MGA(Administrador)'    
admin.site.site_title = 'MGA'    

qnow_user/models.py
import re
from django.db import models
from django.core import validators
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin,
    UserManager)
from datetime import datetime
from django.utils import timezone

class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField('E-mail', unique=True)
    username = models.CharField('Nome', unique=True, max_length=100, blank=False)
    is_active = models.BooleanField('Acessar o Sistema(S/N)', blank=True, default=True)
    is_staff = models.BooleanField('É da equipe?', blank=True, default=False)
    date_joined = models.DateTimeField('Data de Cadastro', auto_now_add=True)
    role = models.CharField('Classificação', max_length=10, blank=True, default='Indefinido')
    phone = models.CharField('Telefone', max_length=50, blank=False)
    cep = models.CharField('Cep', max_length=9, blank=False)
    street = models.CharField('Endereço', max_length=200, blank=False, default='Indefinido')
    district = models.CharField('Bairro', max_length=50, blank=False, default='Indefinido')
    city = models.CharField('Cidade', max_length=50, blank=False, default='Indefinido')
    state = models.CharField('Estado', max_length=50, blank=False, default='Indefinido')

    # Quando definido True, o usuário NÃO PODERÁ interagir/receber emails com o sistema todo(cotações e lances)
    approved = models.BooleanField('Desativar Movimentação', blank=True, default=False)

    contract_accepted = models.BooleanField('Li e concordo(S/N)', blank=True, default=False)
    contract_date_accepted = models.DateTimeField('Li e concordei em:',default=timezone.now)

    # Data de nascimento para client e para a empresa do provider
    birth_date = models.DateField('Data de Inicio das Atividades',blank=True, null=True)

    # Prazo de entrega para provider
    delivery_time = models.CharField('Prazo de Entrega - Padrão',max_length=30,null=True,blank=True)

    # Forma de pagamento para provider 
    form_payment = models.CharField('Forma de Pagamento - Padrão',max_length=50,null=True,blank=True)

    # Informações adicionais para conquistar o cliente
    information = models.TextField('Conquistando o Cliente',max_length=500,blank=True)

    objects = UserManager()


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

    def get_short_username(self):
        return self.username

    def get_full_username(self):
        return str(self)
    
    '''
    # Sub-campo: que retorna a qtde de cotações em diversos stages - PENDENTE
    def get_number_launch_client_pendente(self):
        from qnow_client.models import Quotation,QuotationStage
        qnumber = Quotation.objects.filter(client=self.id,client__role='client',stage_id=QuotationStage.objects.get(status=0).id)
        if qnumber:
            return qnumber.count()
        else:    
            return '--'
    get_number_launch_client_pendente.short_description = "P"     
    
    # Sub-campo: que retorna a qtde de cotações em diversos stages - EM ANALISE
    def get_number_launch_client_analise(self):
        from qnow_client.models import Quotation,QuotationStage
        qnumber = Quotation.objects.filter(client=self.id,client__role='client',stage_id=QuotationStage.objects.get(status=1).id)
        if qnumber:
            return qnumber.count()
        else:    
            return '--'
    get_number_launch_client_analise.short_description = "E"     
    '''

    # Sub-campo: que retorna a qtde de cotações em diversos stages - LIBERADO
    def get_number_launch_client_liberado(self):
        from qnow_client.models import Quotation,QuotationStage
        qnumber = Quotation.objects.filter(client=self.id,client__role='client',stage_id=QuotationStage.objects.get(status=2).id)
        if qnumber:
            return qnumber.count()
        else:    
            return '--'
    get_number_launch_client_liberado.short_description = "L"     

    # Sub-campo: que retorna a qtde de cotações em diversos stages - ORÇADO
    def get_number_launch_client_orcado(self):
        from qnow_client.models import Quotation,QuotationStage
        qnumber = Quotation.objects.filter(client=self.id,client__role='client',stage_id=QuotationStage.objects.get(status=3).id)
        if qnumber:
            return qnumber.count()
        else:    
            return '--'
    get_number_launch_client_orcado.short_description = "O"     

    # Sub-campo: que retorna a qtde de cotações em diversos stages - APROVADO
    def get_number_launch_client_aprovado(self):
        from qnow_client.models import Quotation,QuotationStage
        qnumber = Quotation.objects.filter(client=self.id,client__role='client',stage_id=QuotationStage.objects.get(status=4).id)
        if qnumber:
            return qnumber.count()
        else:    
            return '--'
    get_number_launch_client_aprovado.short_description = "A"     

    # Sub-campo: Indica o tempo em dias ou anos do inicio das atividades do provider
    def get_birth_date_provider(self):
        if self.birth_date:
            date1 = datetime.now().toordinal()
            date2 = self.birth_date.toordinal()
            idade = date1 - date2 
            if idade > 365:
                idade = "+ de % 3.0f ano(s)" % float(idade / 365)
            else:     
                idade =  "% 0.0f mese(s)" % int(float(idade / 365)*10) 
            return idade
        else:     
            return ''
    get_birth_date_provider.short_description = 'Idade da Empresa'  

    
    class Meta:
        app_label = 'qnow_user'
        db_table = 'qnow_user_user'
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

qnow_user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

# Class usada somente para o cadastro e não para o login 
class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmação de Senha', widget=forms.PasswordInput)
    
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação não está correta')
        return password2


    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['email','username','phone', 'cep','street','district','city','state','password1','password1','birth_date','delivery_time','form_payment','information','contract_accepted']

        widgets = {
            'email': forms.TextInput(
                attrs={'placeholder': 'E-mail de contato. Ex: fulano@fulando.com'}
                ),
            'username': forms.TextInput(
                attrs={'placeholder': 'Nome completo. Ex: Fulano da Silva'}
                ),
            'phone': forms.TextInput(
                attrs={'placeholder': 'Fone para contato. Ex: (DD) 99999-9999'}
                ),
            'cep': forms.TextInput(
                attrs={'placeholder': 'Seu CEP. Ex: 99999-999'}
                ),
            'city': forms.TextInput(
                attrs={'placeholder': 'Sua cidade. Ex: Pelotas'}
                ),
            'district': forms.TextInput(
                attrs={'placeholder': 'Seu bairro. Ex: Fragata'}
                ),
            'street': forms.TextInput(
                attrs={'placeholder': 'Sua rua, nº, bloco e apto se possuir'}
                ),
            'state': forms.TextInput(
                attrs={'placeholder': 'Estado de sua cidade. Ex: RS'}
                ),
            'birth_date': forms.DateInput(
                attrs={'type': 'text', 'class': 'datepicker-here date_format', 'data-language': 'pt-BR', 'data-position': 'bottom left', 'data-auto-close': 'true', 'autocomplete':'off',
                    'data-toggle':'tooltip', 'data-placement':'top'
                    }
                ),
            'delivery_time': forms.TextInput(
                attrs={'placeholder': 'Ex: 60 dias úteis'}
                ),
            'form_payment': forms.TextInput(
                attrs={'placeholder': 'Ex: 50% entrada + 50% na entrega'}
                ),
            'information': forms.Textarea(
                attrs={'cols': 40,'style':'width: 100%; height: 100%; resize: none; !important;','title':'',
                    'placeholder': '*** Informe algo assim ***\nEstamos a mais de X anos no mercado de móveis planejados. Trabalhamos com materiais de primeira linha, respeitamos sempre o prazo de entrega e ofertando as melhores condições de pagamento.\n\n*** Proibido colocar o nome da marcenaria ou qualquer outro contato neste campo! ***'
                    }
                )


        }


class EditAccountForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['email','username','phone','cep','city','state','district']

qnow_user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login
from django.template.loader import render_to_string, get_template
from django.utils.safestring import mark_safe
from django.template import Context, RequestContext
from django.contrib import messages
from django.core.mail import EmailMessage, BadHeaderError, EmailMultiAlternatives
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .models import User
import threading
from qnow_client.models import Quotation
from .forms import RegisterForm, EditAccountForm

# Redirect usado pelo template quando client para o correto redirect
def login_client_start(request, *args, **kwargs):
    settings.LOGIN_REDIRECT_URL = 'qnow_client:quotation_client'
    return redirect('qnow_user:login_client')

# Redirect usado pelo template quando provider para o correto redirect
def login_provider_start(request, *args, **kwargs):
    settings.LOGIN_REDIRECT_URL = 'qnow_provider:quotation_provider'
    return redirect('qnow_user:login_provider')

# Transforma a letra de cada palavra em maiusculo
def capitalize_text(name):
    p = ['da', 'de', 'di', 'do', 'du', 'para']
    name = name.lower()
    items = []
    for item in name.split():
        if not item in p:
            item = item.capitalize()
        items.append(item)
    return ' '.join(items)

# def usada somente para registrar o usuários 
def register(request, origin, *args, **kwargs):
    template_name = '../templates/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.role = origin
            user.email = user.email.lower()
            user.username = capitalize_text(user.username)
            '''
            # Por padrão, o provider estará inativo quando no primeiro cadastro
            if origin != 'client':
               user.approved = False
            else:
               user.approved = True
            '''
            user.save()
            user = authenticate(
                email=user.email, password=form.cleaned_data['password1'],backend='django.contrib.auth.backends.ModelBackend'
            )
            login(request, user)

            # Envia um e-mail ao cliente após o cadastro
            t1 = threading.Thread(target=user_email, args=(user,'cadastrado',settings.SEND_EMAIL_SIS))
            t1.start()
            #user_email(user,'cadastrado',settings.SEND_EMAIL_SIS)
            
            if origin == 'client':
                return redirect('qnow_client:quotation_client')
            else:
                return redirect('qnow_provider:quotation_provider')

    else:
        form = RegisterForm()

    context = {
        'active_page_client_provider':'active',
        'origin': origin,
        'form': form
    }
    return render(request, template_name, context)


def user_email(request,acao='ERROR',send_email_sis='False'):
    if send_email_sis == True:
        template_name = "../templates/user_email.html"
        subject = 'MGA-Cotações: '+str(request.username)+' '+acao+' com sucesso!'
        message = 'Parabéns, seu cadastro foi registrado com sucesso!'
        from_email = settings.EMAIL_HOST_USER

        context = {
            "request": request,
            "message":message
            }
        content = render_to_string(template_name, context)

        if subject and message and from_email:
            try:
                email = EmailMessage(
                    subject,
                    content,
                    from_email, 
                    [request.email],
                    ['lgerardlucas@gmail.com','mgacotacoes@gmail.com']
                )
                email.content_subtype = "html"
                email.send(fail_silently=False)
            except BadHeaderError:
                return HttpResponse('Problema no envio do e-mail. Tente mais tarde!')
  

qnow_user/templates/login.html
{% extends "default.html" %}
{% load static %}
{% block content %}


<!-- Page Title -->
<section class="page-title">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-12 title">
				 {% if origin  == "client" %}
		  			<h2>Acesso do Cliente</h2>
				 {% else %}	  
				    <h2>Acesso da Marcenaria</h2>
				 {% endif %}	
				<ol class="breadcrumb">
					<li>Você esta aqui: &nbsp;</li>
					<li><a class="pathway" href="{% url 'qnow_site:site' %}">Home</a></li>
					<li>Acesso à Plataforma</li>
 					 {% if origin  == "client" %}
					   <li class="active">Acesso do Cliente</li>
        			 {% else %}
					   <li class="active">Acesso da Marcenaria</li>
        			 {% endif %}

 				</ol>
			</div>
		</div>
	</div>
</section>

	{% if messages %}
	<div
		style="text-align: center; background-color: #ffb400; width: 100%; height: ; padding-top: 10px; color:white; font-size: 1.2em; line-height: 2px;;">
		<ul>
			{% for message in messages %}
			<li{% if message.tags %} class="{{ message.tags }}" {% endif %}>
				{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
				<h3>{{ message }}</h3>
				</li>
				{% endfor %}
		</ul>
	</div>
	{% endif %}


<!-- Get A Quote -->
<section class="main-body">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-12">
				<article itemtype="#" itemscope="" class="item item-page">
					<meta content="en-GB" itemprop="inLanguage">
					<div itemprop="articleBody">
						<div class="uk-grid">
							<div class="uk-width-medium-1-2">
								<div class="gbs3">

                     			  {% if origin  == "client" %}
  									<form enctype="multipart/form-data" method="POST" name="quote" id="chronoform-quote" class="chronoform">
									<h4>Seja bem vindo!<br><br> Se você <strong>cliente</strong> já esta cadastrado(a), informe seu login e senha e tenha acesso a área de cotação imediatamente.</h4>
								  {% else %} 	  
   									<form enctype="multipart/form-data" method="POST" name="quote" id="chronoform-quote" class="chronoform">
									<h4>Seja bem vindo!<br><br> Se a sua <strong>marcenaria</strong> já esta cadastrada, informe seu login e senha e tenha acesso a área que lista os pedidos de cotações imediatamente.</h4>
								  {% endif %}	   
								        {% csrf_token %}
								   		{{ form.mon_field_erros }}										
										{% for field in form %}
											<div class="form-group" id="form-row-text1">
												<label for="text1" class="control-label required_label">
												{{ field.label_tag }}
													<i class="fa fa-asterisk" style="color:#ff0000; font-size:9px; vertical-align:top;"></i>
												</label>
												<div class="gcore-display-table">
													{{ field }}
													{{ field.errors }}
												</div>
											</div>
										{% endfor %}
										 <div class="form-group" id="form-row-button9">
											<div class="gcore-display-table" id="fin-button9">
												<input name="button9" id="button9" value="Entrar" class="btn btn-default"
													type="submit">
											</div>
										</div>
 									 <div class="form-group" id="form-row-text1">
										<label for="text1" class="control-label required_label">
											Não é cadastrado?
											{% if origin  == "client" %}
												<a href="{% url 'qnow_user:register_client' %}">
											{% else %}	
												<a href="{% url 'qnow_user:register_provider' %}">
											{% endif %}	
												<strong>Cadastre-se</strong></a><br>
												Esqueceu a senha? <a href="{% url 'password_reset' %}"><strong>Redefinir</strong></a><br>
											</label>											
									 </div>	

									</form>
								</div>
							</div>
							<div class="uk-width-medium-1-2">
								{% if origin  == "client" %}
									<h3>O cliente que acessa a MGA-Cotações terá:</h3>
									<h4><strong>01.</strong> Marcenarias</h4>
									<p>	Ao acessar a plataforma MGA-Cotações, você terá uma lista de marcenarias a sua espera. Faça a sua cotação	
										e espere o retorna dos valores e condições que cada uma delas irão informar, tanto aqui como via 
										e-mail.</p>
									<hr>
									<h4><strong>02.</strong> Cotações</h4>
									<p>	Muito mais cotações a sua disposição do que pelo método antigo. Esqueça aquele velho processo,
									    onde você ligaria para uma ou duas marcenarias e aceitaria o valor informado e pronto.</p>
									<hr>
									<h4><strong>03.</strong> Informações</h4>
									<p>	Pela plataforma MGA-Cotações, você terá poder de escolha, e não somente levando em conta o valor, e sim, 
									 	prazo de entrega e formas de pagamento. Nem sempre o valor é prioridade, com isto, as empresas terão que 
										ser justas também nos demais critérios, visando sua consquista.</p>
									<hr>
									<h4><strong>04.</strong>  Objetivo</h4>
									<p>	A MGA-Cotações quer unir vocẽ cliente as melhores marcenarias! Por isto, uma plataforma, que facilite
										o processo de cotação com facilidade e imparcialidade é o nosso principal objetivo.</p>
								{% else %}					   
									<h3>A marcenaria que acessar a MGA-Cotações terá:</h3>
									<h4><strong>01.</strong> Clientes</h4>
									<p>	Ao acessar a plataforma MGA-Cotações, a marcenaria terá muito mais opções de clientes e projetos.
									    Também, estará dentro de um ambiente que prega competitividade, imparcialidade e crescimento, pois
										oferece, um meio de captação de vendas que agrega valores não somente as grandes marcenarias mas
										pequenas e médias também. 
										</p>
									<hr>
									<h4><strong>02.</strong> Cotações</h4>
									<p>	A partir do seu acesso, uma lista de cotações estarão sempre a sua espera. Cotá-las da melhor forma, 
										faz da sua empresa uma referência. E gerar as melhores informações, dá ao cliente a segurança em contratar 
										a mesma.
									    </p>
									<hr>
									<h4><strong>03.</strong> Responsabilidade</h4>
									<p>	A responsabiliade, tanto nas informações geradas em cima das cotaçẽs do cliente escolhido pela marcenaria, 
										como também, o segmento dado após o cliente ter aderido a dita cotação, como: a produação, entrega e pós vendas
										é totalmente da marcenaria. Com isto, ser o mais claro e o mais justo, eleva sua empresa a um patamar competitivo 
										e responsável pra nós da MGA-Cotações!</p>
									<hr>
									<h4><strong>04.</strong>  Objetivo</h4>
									<p>	A MGA-Cotações quer trazer para as empresas do ramo de móveis planejados, um ambiente imparcial, competitivo e justo.
										Queremos uma plataforma que alavanque sua empresa e ao mesmo tempo, à inclua em pé de igualdade, num mercado 
										de tanta concorrência.</p>

								{% endif %}
							</div>

						</div>
					</div>
				</article>
			</div>
		</div>
	</div>
</section>
<!-- /Get A Quote -->

{% endblock %}
<!-- /Contact Us -->

<!-- Bottom B -->
<!-- Footer Top -->
<!-- Footer -->
{% block footer %}
{% endblock %}
<!-- /Bottom B -->
<!-- /Footer Top -->
<!-- /Footer -->