qnow_site/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'qnow_site'

urlpatterns = [
    path('', views.site ,name='site'),
    path('accounts/login/', views.site ,name='site'), 
    path('contact/', views.contact ,name='contact'),
    path('about/', views.about ,name='about'),
    path('blog/', views.blog ,name='blog'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

""" 
O path accounts/login foi usado, para o acesso ao site principal e não a tela de login.
Isto porque, esta plataforma acessa dois tipos de login, o client e provider, para tal,
foram criadas rotas diferentes. Mas ao recuperar a senha, o link padrão, leva para o 
escrito acima e redirecionei ele para abrir o site 
"""

qnow_user/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView,LogoutView
from . import views


app_name = 'qnow_user'

urlpatterns = [
    path('login_client_start/', views.login_client_start, kwargs={'origin': 'client' }, name='login_client_start'),
    path('login_provider_start/', views.login_provider_start, kwargs={'origin': 'provider' }, name='login_provider_start'),
    
    path('login_client/',   LoginView.as_view(template_name='../templates/login.html',
                                     extra_context={'next':'qnow_client:quotation_client',
                                                    'origin':'client',
                                                    'active_page_client_provider':'active'
                                                    }
                                    ), name="login_client"),
    path('login_provider/', LoginView.as_view(template_name='../templates/login.html',
                                     extra_context={'next':'qnow_provider:quotation_provider',
                                                    'origin':'provider',
                                                    'active_page_client_provider':'active'
                                                    }
                                    ), name="login_provider"),

    path('logout/', LogoutView.as_view(template_name='../templates/index.html',
                                    extra_context={'next_page':'qnow_site:site',
                                                   'active_page_site': 'active',
                                    }),name='logout'),

    path('register_client/', views.register, kwargs={'origin': 'client' }, name='register_client'),
    path('register_provider/', views.register, kwargs={'origin': 'provider' }, name='register_provider'),

]

quotation-now/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
import re
from django.contrib.auth import urls,views


urlpatterns = [
    path('', include('qnow_site.urls',namespace='site')),
    path('admin/', admin.site.urls),
    path('accounts/', include('qnow_user.urls',namespace='accounts')),
    path('client/', include('qnow_client.urls',namespace='client')),
    path('provider/', include('qnow_provider.urls',namespace='provider')),
    path('', include('django.contrib.auth.urls')),
    ]

if settings.DEBUG:
    import debug_toolbar
    from django.urls import include
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls,namespace='debug')),
    ] + urlpatterns


#admin.site.site_header = 'Quotation-NOW'    
#admin.site.index_title = 'Q-NOW(Administrador)'    
#admin.site.site_title = 'Q-NOW'    

admin.site.site_header = 'MGA-Cotações'    
admin.site.index_title = 'MGA(Administrador)'    
admin.site.site_title = 'MGA'    

qnow_site/models.py
from django.db import models
from datetime import date

class Contact(models.Model):
    # Usuário do contato
    name = models.CharField('Nome*',max_length=100, blank=False)

    # Data do envio
    date_send = models.DateField('Data do Envio',default=date.today)

    # Email do contato
    email_send = models.EmailField('E-mail*',max_length=100,blank=False)

    # Assunto
    SUBJECTCHOICES = (
    ('Elogio', 'Elogio'),
    ('Diverso', 'Diverso'),
    ('Dúvida', 'Dúvida'),
    ('Reclamação', 'Reclamação'),
    )
    subject_send = models.CharField('Assunto*',choices=SUBJECTCHOICES,max_length=100, blank=False)

    # Texto do email
    message_send  = models.TextField('Mensagem*',blank=False)

    # Cópia ao remetente
    copy_send = models.BooleanField('Enviar cópia',default=True)

    # Email retornado - Reposta ao cliente
    return_send = models.BooleanField('E-mail respondido?',default=False)

    # Texto de resposta ao e-mail do contato
    message_return = models.TextField('Resposta*',blank=False,default='')

    # Data da última ação
    date_update = models.DateField('Última ação',auto_now=True)


    class Meta:
        verbose_name = 'E-mail de contato'
        verbose_name_plural = 'E-mails de contatos'
        ordering = ["-date_send"]

    def __str__(self):
        return str(self.name)

qnow_site/forms.py
from django import forms    
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact

        fields = (
            'name','email_send','subject_send','message_send','copy_send'
        )

        widgets = {
            'name': forms.TextInput(
                attrs={'placeholder': 'Informe seu nome e sobrenome'}
                ),
            'email_send': forms.TextInput(
                attrs={'placeholder': 'Informe seu e-mail de contato'}
                ),
            'message_send': forms.Textarea(
                attrs={'cols': 40,'style':'width: 100%; height: 50%; resize: none; !important;',
                    'placeholder': 
                        'Dúvidas, reclamações, elogios podem ser sanadas nos enviando uma e-mail.\nDeixe o nº do telefone(Whats) que entraremos em contato.'
                    }
            )
        }

qnow_site/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound
from django.template.loader import render_to_string, get_template
from django.core.mail import EmailMessage, BadHeaderError, EmailMultiAlternatives
from .models import Contact
from django.template import Context, RequestContext
from .forms import ContactForm
from django.contrib import messages
from django.contrib.auth import logout
from django.conf import settings
from qnow_user.models import User
from qnow_client.models import Quotation
from django.db.models import Q
import datetime

# Transforma a letra de cada palavra em maiusculo
def capitalize_text(name):
    p = ['da', 'de', 'di', 'do', 'du', 'para']
    name = name.lower()
    items = []
    for item in name.split():
        if not item in p:
            item = item.capitalize()
        items.append(item)
    return ' '.join(items)


# Acessa a tela principal do site
def site(request):
    # Executa logout quanto fora da área de cotação
    logout(request)

    # Pesquisa as cotações com status = 2 a 6 
    quotations = Quotation.objects.filter(stage_id__status__range=[2, 6], removed=False).filter((Q(view_environment_quotation_home=True, image_environment__isnull=False) | Q(view_project_quotation_home=True, image_project__isnull=False))).order_by('-date_create', '-id')[:20]

    context = {'active_page_site': 'active',
                'quotation_list': quotations
        }
    return render(request, '../templates/index.html',context)

# Acesso a tela de sobre do site  
def about(request):
    # Executa logout quanto fora da área de cotação
    logout(request)

    context = {'active_page_about' : 'active'}
    return render(request, '../templates/about.html',context)

# Acesso a tela de blog
def blog(request):
    # Executa logout quanto fora da área de cotação
    logout(request)

    context = {'active_page_blog' : 'active'}
    return render(request, '../templates/blog.html',context)

# Gravar o e-mail enviado pela tela de contato
def contact(request):
    template_name = '../templates/contact.html'
    form =  ContactForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            Contact = form.save(commit=False)
            Contact.name = capitalize_text(Contact.name)
            Contact.email_send = Contact.email_send.lower()
            form.save()

            # Após salvar, enviar um email ao cliente e uma mensagem na tela
            message_bory = 'E-mail enviado com sucesso!'
            contact_email(Contact)
            messages.add_message(request, messages.SUCCESS, message_bory)

            form = ContactForm()
        else:
            form = ContactForm(request.POST)
    else:
        form = ContactForm()
    context = {
        'active_page_contact' : 'active',
        'form': form
    }
    # Executa logout quanto fora da área de cotação
    logout(request)
    
    return render(request, template_name,context)

# Envia um email referente ao contato do site
def contact_email(request):
    template_name = "../templates/contact_email.html"
    subject = 'MGA-Cotações'
            
    from_email = settings.EMAIL_HOST_USER
    context = {
        "name_send": request.name,
        "assunto_send": request.subject_send,
        "message_send": request.message_send,
        }

    content = render_to_string(template_name, context)

    if subject and from_email:
        try:
            if request.copy_send:
                email_copy = request.email_send
            email = EmailMessage(
                subject,
                content,
                from_email, 
                [email_copy,'lgerardlucas@gmail.com'],
            )
            email.content_subtype = "html"
            email.send(fail_silently=False)
        except BadHeaderError:
            return HttpResponse('Problema no envio do e-mail. Tente mais tarde!')

qnow_site/templates/about.html
{% extends "default.html" %}
{% load static %}
{% block content %}
<!-- Page Title -->
<section class="page-title">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-12 title">
				<h2>Sobre nós</h2>
				<ol class="breadcrumb">
					<li>Você esta aqui: &nbsp;</li>
					<li><a class="pathway" href="{% url 'qnow_site:site' %}">Home</a></li>
					<li class="active">Sobre</li>
				</ol>
			</div>
		</div>
	</div>
</section>
<!-- /Page Title -->

<!-- Top A -->
<section class="top-a">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-12">
				<div class="module title3">
					<div class="module-content">
						<div class="uk-grid uk-margin-bottom">
							<div class="uk-width-medium-1-3">
             					<h3 class="module-title">Nossa plataforma</h3>
								<p><img width="100%" alt="Sobre nós" src="{% static '/images/logo-about.png' %}"></p>
							</div>
							<div class="uk-width-medium-1-3" style="text-align:justify">
             					<h3 class="module-title">O que oferecemos?</h3>
								<p class="dropcap">A <strong>MGA-Cotações</strong>  
									é uma plataforma de cotação online para um nicho de 
									mercado muito importante, neste caso Móveis Planejados. Temos a intenção de oferecer um mecanismo de cotação que 
									unirá <strong>CLIENTES e MARCENARIAS</strong> em um só ambiente, dando a ambas as partes uma experiência simples e 
									eficaz tanto para o <strong>CLIENTE</strong> que busca os melhores preços, prazos de entrega e condições de pagamento, como para <strong>MARCENEIROS</strong> 
									colocando-os em condições iguais neste mercado com tanta concorrência.
								</p>
							</div>
							<div class="uk-width-medium-1-3" style="text-align:justify">
             					<h3 class="module-title">Qual o nosso objetivo?</h3>
									Objetivamos ter uma forma simplificada de um sistema de cotação para um nicho de mercado importantíssimo, que são os de móveis planejados. 
									Onde desejamos oferecer aos clientes empresas que se destaquem em qualidade de serviço com preços competitivos e com facilidade na forma 
									de pagamento. Hoje, este segmento agrega um valor importante a seus produtos pois oferecem um processo de industrialização que respeita totalmente 
									o desejo do cliente na produção. Tendo em vista esta regra de negócio é importante ter um local onde <strong>MARCENARIAS</strong> e <strong>CLIENTES</strong>
									possam trocar informações com qualidade em um ambiente seguro e imparcial.							        
						
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- /Top A -->

<!-- Top B -->
<section class="top-b">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-12">
				<div class="module title3">
					<h3 class="module-title">Porque utilizar esta plataforma?</h3>
					<div class="module-content">
						<div class="uk-grid uk-text-center">
							<div class="uk-width-medium-1-3">
								<div class="uk-panel uk-panel-box uk-panel-box-secondary uk-panel-hover">
									<i class="pe-7s-portfolio pe-4x pe-va"></i>
									<h4>Marcenarias</h4>
									<p>As melhores empesas do segmento de móveis planejados estarão aqui.</p>
								</div>
							</div>
							<div class="uk-width-medium-1-3">
								<div class="uk-panel uk-panel-box uk-panel-box-secondary uk-panel-hover">
									<i class="pe-7s-vector pe-4x pe-va"></i>
									<h4>Facilidade</h4>
									<p>Possuimos uma ferramente simples e eficaz para cotações.</p>
								</div>
							</div>
							<div class="uk-width-medium-1-3">
								<div class="uk-panel uk-panel-box uk-panel-box-secondary uk-panel-hover">
									<i class="pe-7s-rocket pe-4x pe-va"></i>
									<h4>Comunicação</h4>
									<p>Interligamos CLIENTES e MARCENARIAS facilitando a negociação.</p>
								</div>
							</div>
						</div>
						<div class="uk-grid uk-text-center">
							<div class="uk-width-medium-1-3">
								<div class="uk-panel uk-panel-box uk-panel-box-secondary uk-panel-hover">
									<i class="pe-7s-magic-wand pe-4x pe-va"></i>
									<h4>Uma única ideia</h4>
									<p>O CLIENTE gera uma cotação e as MARCENARIAS informam os preços.</p>
								</div>
							</div>
							<div class="uk-width-medium-1-3">
								<div class="uk-panel uk-panel-box uk-panel-box-secondary uk-panel-hover">
									<i class="pe-7s-tools pe-4x pe-va"></i>
									<h4>Materiais e Qualidade</h4>
									<p>Primamos por MARCENARIAS que utilizam materiais de primeira linha.</p>
								</div>
							</div>
							<div class="uk-width-medium-1-3">
								<div class="uk-panel uk-panel-box uk-panel-box-secondary uk-panel-hover">
									<i class="pe-7s-ribbon pe-4x pe-va"></i>
									<h4>Garantia</h4>
									<p>Garantimos a segurança dos dados gravados nesta plataforma.</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- /Top B -->
<!-- /Our Latest Projects -->
<!-- /Testimonials -->
<!-- Bottom -->
<!-- /Bottom -->
{% endblock %}
<!-- Bottom B -->
<!-- Footer Top -->
<!-- Footer -->
{% block footer %}
{% endblock %}
<!-- /Bottom B -->
<!-- /Footer Top -->
<!-- /Footer -->

qnow_site/templates/blog.html
{% extends "default.html" %}
{% load static %}
{% block content %}

<!-- Page Title -->
<section class="page-title">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-12 title">
				<h2>Blog</h2>
				<ol class="breadcrumb">
					<li>Você esta aqui: &nbsp;</li>
					<li><a class="pathway" href="{% url 'qnow_site:site' %}">Home</a></li>
					<li class="active">Blog</li>
				</ol>
			</div>
		</div>
	</div>
</section>
<!-- /Page Title -->

<!-- Blog -->
<section class="main-body">
	<div class="container">
		<div class="row">
			<div class="col-sm-9 col-md-9 left">
				<div itemtype="http://schema.org/Blog" itemscope="" class="blog">
					<div class="row clearfix">

						<div class="col-sm-6">
							<article itemtype="http://schema.org/BlogPosting" itemscope="" itemprop="blogPost" class="item ">
								<div class="entry-header has-post-format">
									<span class="post-format"><i class="fa fa-thumb-tack"></i></span>
									<dl class="article-info">
										<dt class="article-info-term"></dt>
										<dd class="category-name">
											<i class="fa fa-folder-open-o"></i>
											<a title="" data-toggle="tooltip" itemprop="genre" href="{% url 'qnow_site:blog' %}"
												data-original-title="Article Category">Blog</a>
										</dd>
										<dd class="published">
											<i class="fa fa-calendar-o"></i>
											<time title="" data-toggle="tooltip" itemprop="datePublished" datetime="2015-11-10T08:14:20+00:00"
												data-original-title="Published Date">
												15 Julho 2019
											</time>
										</dd>
										<dd class="post_rating">
											Avaliação:
											<div class="voting-symbol">
												<span data-number="5" class="star active"></span><span data-number="4"
													class="star active"></span><span data-number="3" class="star active"></span><span
													data-number="2" class="star active"></span><span data-number="1" class="star active"></span>
											</div>
										</dd>
									</dl>
									<h2 itemprop="name">
										<a itemprop="url" href="#">Simplicidade e Beleza!</a>
									</h2>
								</div>
								<p><img src="{% static '/images/blog/blog5.jpg' %}" alt="Simplecidade e Beleza!" width="90%"></p>
								<p>Mesmo em ambientes pequenos sendo eles residenciais ou de trabalho, a simplicidade em forma de móveis 
									embeleza. Hoje podemos ver um ambiente de trabalho funcional e ao mesmo tempo leve, sem deixar o espaço carregado. 
									</p>
								<hr>
							</article>
							<!-- end item -->
						</div><!-- end col-sm-* -->

					<div class="col-sm-6">
							<article itemtype="http://schema.org/BlogPosting" itemscope="" itemprop="blogPost" class="item ">
								<div class="entry-header has-post-format">
									<span class="post-format"><i class="fa fa-thumb-tack"></i></span>
									<dl class="article-info">
										<dt class="article-info-term"></dt>
										<dd class="category-name">
											<i class="fa fa-folder-open-o"></i>
											<a title="" data-toggle="tooltip" itemprop="genre" href="{% url 'qnow_site:blog' %}"
												data-original-title="Article Category">Blog</a>
										</dd>
										<dd class="published">
											<i class="fa fa-calendar-o"></i>
											<time title="" data-toggle="tooltip" itemprop="datePublished" datetime="2015-11-10T08:14:20+00:00"
												data-original-title="Published Date">
												20 Julho 2019
											</time>
										</dd>
										<dd class="post_rating">
											Avaliação:
											<div class="voting-symbol">
												<span data-number="5" class="star active"></span><span data-number="4"
													class="star active"></span><span data-number="3" class="star active"></span><span
													data-number="2" class="star active"></span><span data-number="1" class="star active"></span>
											</div>
										</dd>
									</dl>
									<h2 itemprop="name">
										<a itemprop="url" href="#">Simplicidade e Beleza!</a>
									</h2>
								</div>
								<p><img src="{% static '/images/blog/blog4.jpg' %}" alt="Simplecidade e Beleza!" width="80%"></p>
								<p>Ambientes deixam de ser simples quando vimos o conjunto da obra completo. Estou 
									me referindo a esta bela cozinha, onde estilo e beleza fecham com chave de ouro qualquer ambiente familiar.
									</p>
								<hr>
							</article>
						</div>
					</div>

<!-- 
 					<div class="pagination-wrapper">
						<p class="counter"> Page 1 of 2 </p>
						<ul class="pagination">
							<li class="active"><a>1</a></li>
							<li><a title="2" href="blog2.html" class="">2</a></li>
							<li><a title="»" href="blog2.html" class="next">»</a></li>
							<li><a title="End" href="blog2.html" class="">End</a></li>
						</ul>
					</div> -->


 				</div>
			</div>
		</div>
	</div>
</section>
<!-- /Blog -->

<!-- Get A Quote -->
<section class="parallax-section-2">
	<div class="row">
		<div class="col-sm-12 col-md-12" id="parallax2">
			<div class="module ">
				<div class="module-content">
					<div class="uk-text-contrast uk-flex uk-flex-center" data-uk-parallax="{bg: -300}"
						style="min-height: 160px; background-color: rgb(41, 44, 47); background-repeat: no-repeat; background-size: cover; background-position: 50% -42.435px;">
						<div class="container1170" style="padding:20px 15px;">
							<div class="uk-grid">
								<div class="uk-width-medium-3-4">
									<br>
									<h3 embed-responsive-item style="margin-top pull-left:15px;">
										MGA-Cotações é uma plataforma que une cliente as melhores marcenarias.<br>
										
									</h3>
								</div>
								<div class="uk-width-medium-1-4 uk-text-right inverted">
									<h3 embed-responsive-item style="margin-top pull-left:5px;">
										{% if user.is_authenticated %}
										<a href="{% url 'qnow_user:login_client_start' %}" class="uk-button raleway16">Inicie sua cotação
											aqui!</a>
										{% else %}
										<br>
										<a class="uk-button raleway16" href="{% url 'qnow_user:login_client_start' %}">Acesso à Plataforma
											</a>
										{% endif %}
									</h3>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- /Get A Quote -->

<!-- Bottom B -->
{% endblock %}
<!-- Bottom B -->
<!-- Footer Top -->
<!-- Footer -->
{% block footer %}
{% endblock %}
<!-- /Bottom B -->
<!-- /Footer Top -->
<!-- /Footer -->

qnow_site/templates/contact.html
{% extends "default.html" %}
{% load static %}
{% block content %}

<!-- Page Title -->
<section class="page-title">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-12 title">
				<h2>Entre em contato</h2>
				<ol class="breadcrumb">
					<li>Você esta aqui: &nbsp;</li>
					<li><a class="pathway" href="{% url 'qnow_site:site' %}">Home</a></li>
					<li class="active">Contato</li>
				</ol>
			</div>
		</div>
	</div>
</section>


		<!--Messagem diversas-->
{% if messages %}
		<div class="container">
			<div class="module title5" style="text-align: center">
				<ul>
					{% for message in messages %}
						{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
						<h3>{{ message }}</h3>
					{% endfor %}
				</ul>
			</div>
		</div>

{% endif %}

<section class="main-body">
	<div class="container">
		<div class="row">
			<div class="col-sm-9 col-md-9">
				<h3>Contato</h3>
				<form class="form-horizontal" method="POST">
					{% csrf_token %}
					{{ form.mon_field_errors }}
						<legend>Envie seu e-mail. Todos os campos com (*) são de preenchimento obrigatório.</legend>
						<fieldset>
							{% for field in form %}
									<div class="form-group">
										<label for="inputName" class="control-label label-left col-xs-3">{{ field.label }}</label>
										<div class="col-xs-9">
											<div class="gcore-display-table">
												{{ field }}
												{{ field.errors }}
											</div>
										</div>
									</div>
							{% endfor %}
							<div class="form-group">
									<label class="control-label label-left col-xs-3"></label>
									<div class="col-xs-9">
<!-- 										
										<button class="btn btn-primary validate" type="submit" aria-invalid="false">Enviar
											E-mail
										</button>
 -->
 										<input name="button9" id="button9" value="Envia E-mail" class="btn btn-default uk-button uk-button-default demo"
										type="submit">
									</div>
								</div>
		
						</fieldset>
				</form>
			</div>
			
			<div class="col-sm-3 col-md-3" id="left">
				<div class="module title6">
					<div class="module-content">
						<h4><strong>Tem dúvidas de como fazer suas cotações?</strong></h4>
						<hr>
						<i class="pe-7s-pin pe-3x uk-text-primary"></i>
						<h4>Pelotas - RS - Brasil</h4>
						<hr>
						<i class="pe-7s-phone pe-3x uk-text-primary"></i>
						<h4>(53) 98121-5585</h4>
						<hr>
						<i class="pe-7s-mail pe-3x uk-text-primary"></i>
						<h4>mgacotacoes@gmail.com</h4>
						<hr>
						<br>
						<br>
						<br>
						<br>
			
					</div>
				</div>
			</div>

		</div>
	</div>
</section>

{% endblock %}
{% block footer %}
{% endblock %}

qnow_site/templates/template_lucas.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Flex</title>

    <style>
        body {
            margin: 0;
        }
        .navbar {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid black;
        }
    </style>
</head>

<body>
    <div class="navbar">
        <img class="logo" width="100" height="50"
            src="https://images.fastcompany.net/image/upload/w_596,c_limit,q_auto:best,f_auto/fc/3034007-inline-i-applelogo.jpg">

        <div class="menu">teste</div>
        <div class="menu">teste</div>
    </div>
</body>

</html>