qnow_provider/urls.py
from django.urls import path, include
from . import views

app_name = 'qnow_provider'

urlpatterns = [
  path('quotation_provider/', views.quotation_provider ,name='quotation_provider'),
  path('quotation_provider_detail/<int:quotation_id>', views.quotation_provider_detail ,name='quotation_provider_detail'),
  path('quotation_provider_price/<int:quotation_id>', views.quotation_provider_price ,name='quotation_provider_price'),
  path('quotation_provider_price_post/<int:quotation_id>', views.quotation_provider_price_post ,name='quotation_provider_price_post'),
  path('quotation_provider_email_inquire/<int:quotation_id>', views.quotation_provider_email_inquire ,name='quotation_provider_email_inquire'),
]

qnow_site/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'qnow_site'

urlpatterns = [
    path('', views.site ,name='site'),
    path('accounts/login/', views.site ,name='site'), 
    path('contact/', views.contact ,name='contact'),
    path('about/', views.about ,name='about'),
    path('blog/', views.blog ,name='blog'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

""" 
O path accounts/login foi usado, para o acesso ao site principal e não a tela de login.
Isto porque, esta plataforma acessa dois tipos de login, o client e provider, para tal,
foram criadas rotas diferentes. Mas ao recuperar a senha, o link padrão, leva para o 
escrito acima e redirecionei ele para abrir o site 
"""

qnow_user/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView,LogoutView
from . import views


app_name = 'qnow_user'

urlpatterns = [
    path('login_client_start/', views.login_client_start, kwargs={'origin': 'client' }, name='login_client_start'),
    path('login_provider_start/', views.login_provider_start, kwargs={'origin': 'provider' }, name='login_provider_start'),
    
    path('login_client/',   LoginView.as_view(template_name='../templates/login.html',
                                     extra_context={'next':'qnow_client:quotation_client',
                                                    'origin':'client',
                                                    'active_page_client_provider':'active'
                                                    }
                                    ), name="login_client"),
    path('login_provider/', LoginView.as_view(template_name='../templates/login.html',
                                     extra_context={'next':'qnow_provider:quotation_provider',
                                                    'origin':'provider',
                                                    'active_page_client_provider':'active'
                                                    }
                                    ), name="login_provider"),

    path('logout/', LogoutView.as_view(template_name='../templates/index.html',
                                    extra_context={'next_page':'qnow_site:site',
                                                   'active_page_site': 'active',
                                    }),name='logout'),

    path('register_client/', views.register, kwargs={'origin': 'client' }, name='register_client'),
    path('register_provider/', views.register, kwargs={'origin': 'provider' }, name='register_provider'),

]

quotation-now/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
import re
from django.contrib.auth import urls,views


urlpatterns = [
    path('', include('qnow_site.urls',namespace='site')),
    path('admin/', admin.site.urls),
    path('accounts/', include('qnow_user.urls',namespace='accounts')),
    path('client/', include('qnow_client.urls',namespace='client')),
    path('provider/', include('qnow_provider.urls',namespace='provider')),
    path('', include('django.contrib.auth.urls')),
    ]

if settings.DEBUG:
    import debug_toolbar
    from django.urls import include
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls,namespace='debug')),
    ] + urlpatterns


#admin.site.site_header = 'Quotation-NOW'    
#admin.site.index_title = 'Q-NOW(Administrador)'    
#admin.site.site_title = 'Q-NOW'    

admin.site.site_header = 'MGA-Cotações'    
admin.site.index_title = 'MGA(Administrador)'    
admin.site.site_title = 'MGA'    

qnow_provider/views.py
from django.shortcuts import render, redirect, Http404, render_to_response, get_list_or_404, get_object_or_404
from django.http import HttpResponse, HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from django.utils.safestring import mark_safe
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login,logout
from django.http import HttpResponseRedirect
from django.conf import settings
from django.core.mail import EmailMessage, BadHeaderError, EmailMultiAlternatives
from django.template.loader import render_to_string, get_template
import threading
from datetime import datetime,date,timedelta
from django.contrib import messages
from qnow_client.models import Quotation, QuotationStage
from .forms import QuotationPriceForm
from .models import QuotationPrice
from qnow_user.models import User
from django.db.models import Q
from qnow_site.utils import convert_date_to_br

# Lista as cotações de todos os clients com status = 2(Liberado para orçar)
@login_required
def quotation_provider(request):
    template_name = "../templates/provider_quotation_list.html"

    # Verifica o acesso do cliente na opção provider, força a entrar corretamente
    if request.user.role == 'client':
        # Messagem de alerta, onde o cliente usa o acesso errado a plataforma
        messages.add_message(request, messages.INFO, 'Desculpe, acesso restrito a marcenarias!')
        messages.add_message(request, messages.INFO, 'Tente novamente aqui e agora.')

        # Executa logout quanto fora da área de cotação
        logout(request)

        settings.LOGIN_REDIRECT_URL = 'qnow_client:quotation_client'
        return redirect('qnow_user:login_client')

    # GET - Status da cotação a ser pesquisado
    queryset_stage = request.GET.get('stage_list')

    # GET - Cidade ser pesquisado as cotações
    queryset_city = request.GET.get('city_list')

    # GET - Estado ser pesquisado as cotações
    queryset_state = request.GET.get('state_list')

    # Sub-campos: Retorna o valor de cada cotação referente ao provider 
    def get_price_provider(self):
        if self.quotation_provider == User.id:
            return 1
        else:
            return 2
    get_price_provider = 'Valor'     

    # GET - Por diversos campos
    queryset = request.GET.get('q')
    if queryset or queryset_stage or queryset_city or queryset_state:
        # -1 = Todos ou X para individual
        if queryset_stage == '-1':
            stage_list_start = 2
            stage_list_stop  = 6
        else:
            stage_list_start = queryset_stage
            stage_list_stop  = queryset_stage

        if not queryset_city:
            queryset_city = ''

        if not queryset_state:
            queryset_state = ''

        # Pesquisa via Like + Or
        quotations = Quotation.objects.filter(
            Q(id__icontains=queryset)|
            Q(client__username__icontains=queryset)|
            Q(date_create__icontains=queryset)|            
            Q(house_type__icontains=queryset)|
            Q(house_set__icontains=queryset)|  
            Q(mobile_type__description__icontains=queryset)|
            Q(mobile_description__icontains=queryset)).filter(
            Q(client__city__icontains=queryset_city)).filter(
            Q(client__state__icontains=queryset_state)
            ).filter(stage_id__status__range=[stage_list_start,stage_list_stop],removed=False).order_by('client__city','id')
    else:
        # GET - Status da cotação a ser pesquisado
        queryset_stage = '-1'
        
        # GET - Cidade ser pesquisado as cotações
        queryset_city = ''

        # GET - Estados ser pesquisado as cotações
        queryset_state = ''

        # Pesquisa as cotações com status = 2 a 6 
        quotations = Quotation.objects.filter(stage_id__status__range=[2,6],removed=False).order_by('client__city','id')
    
    # Lista dos status liberados para uso na tag SELECT
    quotationsstages = QuotationStage.objects.filter(status__range=[2,6]).order_by('status')

    # Lista das cidades liberados para uso na tag SELECT
    quotationscitys = User.objects.filter().order_by('city').distinct('city')

    # Lista dos estados liberados para uso na tag SELECT
    quotationsstates = User.objects.filter().order_by('state').distinct('state')

    # Lambda que retorna a quantidade de dados para ser listados
    if quotations.count() > 0:
        message = ''
    else:
        message = 'Nenhuma cotação encontra!'

    # Verifica se encontrou e renderiza
    if Quotation.id:
        context = { "active_page_client_provider": "active", 
                    "message": message,
                    "provider_email": request.user.email,
                    "quotationstage_select":str(queryset_stage),
                    "quotationcity_select":queryset_city,
                    "quotationstate_select":queryset_state,
                    "quotations": quotations,
                    "quotationsstages": quotationsstages,
                    "quotationscitys": quotationscitys,
                    "quotationsstates": quotationsstates
                }
        return render(request, template_name, context)

# Mostra os detalhes e caracteristicas de uma cotação específica
@login_required            #(login_url="/accounts/login_provider/")
def quotation_provider_detail(request,quotation_id=0):
    template_name = "../templates/provider_quotation_detail.html"


    # Pesquisa pelo seu id
    quotation = Quotation.objects.filter(pk=quotation_id,removed=False)

    # Lambda que retorna a quantidade de dados para ser listados
    if quotation.count() > 0:
        message = ''
    else:
        message = str(request.user) + ', Nenhuma cotação disponível para cotação!'

    # Verifica se encontrou e renderiza
    if Quotation.id:
        context = { "active_page_client_provider": "active", 
                    "message": message,
                    "quotation": quotation}
        return render(request, template_name, context)


# Mostra alguns detalhes com fotos menores e campos para cotar
@login_required
def quotation_provider_price(request,quotation_id=0):
    template_name = "../templates/provider_quotation_price.html"
                                                                                                                                
    # GET - Verifica se a cotação tem orçamento
    try:
        quotationprice = QuotationPrice.objects.filter(quotation_number_id=quotation_id,quotation_provider=request.user).count()
    except QuotationPrice.DoesNotExist:
        quotationprice = 0

    # GET - Retorna se o provider tem cotações aprovadas mas não pagou a tempo determinado a comissão a plataforma - Somente é testada cotações cuja o status = "Aprovado". Outras não valerão
    try:                        
        quotationprice_payment_validate = QuotationPrice.objects.filter(quotation_number__stage=29, quotation_provider=request.user,approved=True,commission_paid=False,commission_paid_date__lt=datetime.now()).count()   
    except QuotationPrice.DoesNotExist:
        quotationprice_payment_validate = 0

    # GET - Retorna dados cotação como um todo
    quotation = Quotation.objects.filter(pk=quotation_id,removed=False)
  
    # Teste = Se não tiver cotação por parte do provider mas ele estiver devendo, não enviar os dados de preenchimento padrão pra tela de orçamento
    if quotationprice == 0 and quotationprice_payment_validate != 0:
        form = QuotationPriceForm(request.POST or None, initial={'quotation_number':quotation_id,'quotation_provider':request.user})
    else:    
        form = QuotationPriceForm(request.POST or None, initial={'quotation_number':quotation_id,'quotation_provider':request.user,'date_create':convert_date_to_br(quotation[0].date_create),'delivery_time':request.user.delivery_time,'form_payment':request.user.form_payment})

    # Se tiver orçamento, retorna queryset com os dados e monta o form
    if quotationprice_payment_validate != 0 or quotationprice != 0:
        # Monta os dados a ser mostrado quando já orçado
        if quotationprice != 0:
            quotationprice = QuotationPrice.objects.get(quotation_number_id=quotation_id,quotation_provider=request.user)        
            form = QuotationPriceForm(instance=quotationprice)
        
    # Enviando o context para o template
    context = { "active_page_client_provider": "active", 
                "quotation": quotation,
                "quotationprice":form,
                "qpayment_count":quotationprice_payment_validate
            }
    return render(request, template_name, context)

# Grava o valor orçado pelo provider logado 
@login_required
def quotation_provider_price_post(request,quotation_id=0):
    template_name = "../templates/provider_quotation_price.html"
    if request.method == "POST":
        
        form = QuotationPriceForm(request.POST or None)
        if form.is_valid():     
            post = form.save(commit=False)
            post.date_create = datetime.now()
            try:
                # Retorna o stage(estágio)-Quando houver um lance mudamos o stage para 3 orçado
                quotationstage  = QuotationStage.objects.get(status=3)

                # GET - Retorna dados cotação com um todo
                quotation = Quotation.objects.get(pk=quotation_id,removed=False)

                # Altera para o stage = 3 orçado
                if quotation.stage_id != quotationstage.id:
                    quotation.stage_id  = quotationstage.id
                    quotation.save()

                # Após salvar, enviar um email ao cliente/fornecedor e uma mensagem na tela
                messages.add_message(request, messages.INFO, 'Cotação Nº: '+str(quotation.id)+' orçada com sucesso!')

                t1 = threading.Thread(target=quotation_provider_email, args=(
                    quotation,                      # Dados dos cliente

qnow_provider/templates/provider_quotation_detail.html
{% extends "default.html" %}
{% load static %}
{% load tags %}
{% block content %}
<section class="page-title">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-12 title">
				<h2>Cotações - {{ user.username }}</h2>
				<ol class="breadcrumb">
					<li>Você esta aqui: &nbsp;</li>
					<li><a class="pathway" href="{% url 'qnow_site:site' %}">Home</a></li>
					<li><a class="pathway" href="{% url 'qnow_provider:quotation_provider' %}">Lista de Cotações</a></li>
					<li class="active">Detalhes da Cotação</li>
				</ol>
			</div>
		</div>
	</div>
</section>

<section>
	{% if messages %}
		<div style="text-align: center; background-color: #ffb400; width: 100%; height: 4.2em; padding-top: 10px; color:white; font-size: 1.2em; line-height: 2px;;">
			<ul>
				{% for message in messages %}
				<li{% if message.tags %} class="{{ message.tags }}" {% endif %}>
					{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
					<h3>{{ message }}</h3>
					</li>
					{% endfor %}
			</ul>
		</div>
	{% endif %}


	{% if quotation.count == 0 %}
	<div class="header_provider">
		<div style="text-align: center">
			<strong style="font-size: 24px;">Nenhuma cotação!<br>Informaremos por e-mail</strong>
		</div>
	</div>
	{% else %}

	<div class="mestre">
		{% for field in quotation %}

		<div style="display: inline-block; width: 100%; text-align: center; background-color:#292c2f; height: 2.8em;">
			<h2><strong style="font-size: 24px;">Cotação Nº: {{ field.id }}</strong></h2>
		</div>

		<!-- Móvel e Nº da cotação -->
		<div style="display: inline-block; text-align: left; width: 29em; padding: 0px 15px 0px;">
			<div class="entry-header" style="margin-bottom: 0px;">
				<div class="module title3;">
					<dd style="font-size: 1.4em;">
						<strong style="font-size: 1.6em;">Dados da Cotação</strong><br>
						<!-- Nº da cotação -->
						<strong style="color: #292c2f;">Nº: {{ field.id }}</strong><br>

						<!-- Móvel -->
						<strong style="color: #292c2f;">Móvel:
							{% if field.mobile_type|lower == '_Outro'|lower %}
							{{ field.mobile_description|truncatechars:15 }}
							{% else %}
							{{ field.mobile_type|truncatechars:15 }}
							{% endif %}
						</strong>
						<br>
						<strong style="color: #292c2f;">Situação: {{ field.stage|truncatechars:10 }}</strong>
						<br>
						<strong style="color: #292c2f;">Data:
							{{ field.date_create|date:'SHORT_DATE_FORMAT' }}
						</strong>
						<br>
						<div style="text-align: center; line-height: 1.1em; border: 1px dashed #292c2f; border-radius: 10px; padding-top: 5px; width: 100%; background-color:#292c2f;">
								<strong style="color:white; font-size: 1.0em">
									{% get_status field user.id field.stage.status field.get_number_launch field.get_dif_date_now as state_quotation %}
									{{ state_quotation }}
								</strong>

							<p class="readmore">
								{% if user.is_authenticated %}
									{% if field.stage.status == 2 %}
										{% if 'R$' in state_quotation %}
											<a class="uk-button raleway16" href="{% url 'qnow_provider:quotation_provider' %}">Voltar à Lista de Cotações</a>
										{% else %}
											<a class="uk-button" href="{% url 'qnow_provider:quotation_provider_price' field.id  %}">Inclua seu orçamento aqui.</a>
										{% endif %}
									{% endif %}
								{% endif %}
							</p>
							</strong>
						</div>
					</dd>

					<dd style="font-size: 1.4em;">
						<strong style="font-size: 1.6em;">Dados do Cliente</strong><br>
						<strong style="color: #292c2f;">
							Cliente: {{ field.client|truncatechars:10 }}<br>
							Imóvel: {{ field.house_type|truncatechars:30 }}<br>
							Cidade: {{ field.client.city|truncatechars:35 }}
						</strong>

					</dd>

					<!-- Voltar a lista de cotações -->
					<div style="text-align: center; padding-top: 10px;">
						<p class="readmore">
							{% if user.is_authenticated %}
								<a class="uk-button raleway16" href="{% url 'qnow_provider:quotation_provider' %}">Voltar à Lista de Cotações</a>
								{% if field.stage.status != 4 and field.stage.status != 5 and field.stage.status != 6  %}
									<!-- Enviar uma pergunta ao cliente-->
									<input  name="button9" value="Dúvidas?" class="uk-button raleway16" 
										type="button" data-toggle="modal" data-target="#emailModal_Provider">
								{% endif %}		
							{% else %}
								<a href="{% url 'qnow_user:login_client_start' %}" class="uk-button" style="padding: 3px 3px;">Logar no sistema!</a>
							{% endif %}

							
						</p>
					</div>
				</div>

			</div>
		</div>
		

		<!-- Imagem do ambiente -->
		<div style="display: inline-block; text-align: center; padding: 5px;">
			<div style="display: inline-block; text-align: center; padding: 5px; ">
				{% if field.image_environment|lower == 'None'|lower %}
				<a title="Sem foto do ambiente<br>Situação: {{ field.stage }} - Cotação Nº: {{ field.id }}<br><br><br>"
					data-uk-lightbox="{group:'group1'}" href="{% static '/images/no-image.png' %}">
					<img class="uk-border-rounded" alt="MGA-Cotações<br>Sem foto do ambiente"
						style="height: 25em; width: 26em;" src="{% static '/images/no-image.png' %}">
					<strong style="color:#292c2f;">Ambiente</strong>
				</a>
				{% elif field.image_environment|lower != 'None'|lower %}
				<a title="Foto do seu ambiente<br>Situação: {{ field.stage }} - Cotação Nº: {{ field.id }}<br><br><br>"
					data-uk-lightbox="{group:'group1'}" href="{{ field.image_environment.url }}">
					<img class="uk-border-rounded" alt="MGA-Cotações<br>Foto do ambiente"
						style="height: 25em; width: 26em;" src="{{ field.image_environment.url }}">
					<strong style="color:#292c2f;">Ambiente</strong>
				</a>
				{% endif %}
			</div>
			<!-- Imagem do projeto -->
			<div style="display: inline-block; text-align: center; padding: 5px; ">

				{% if field.image_project|lower == 'None'|lower %}
				<a title="Sem foto do projeto<br>Situação: {{ field.stage }} - Cotação Nº: {{ field.id }}<br><br><br>"
					data-uk-lightbox="{group:'group1'}" href="{% static '/images/no-image.png' %}">
					<img class="uk-border-rounded" alt="MGA-Cotações<br>Sem foto do projeto"
						style="height: 25em; width: 26em;" src="{% static '/images/no-image.png' %}">
					<strong style="color:#292c2f;">Projeto</strong>
				</a>
				{% elif field.image_project|lower != 'None'|lower %}
				<a title="Foto do seu projeto<br>Situação: {{ field.stage }} - Cotação Nº: {{ field.id }}<br><br><br>"
					data-uk-lightbox="{group:'group1'}" href="{{ field.image_project.url }}">
					<img class="uk-border-rounded" alt="MGA-Cotações<br>Foto do projeto"
						style="height: 25em; width: 26em;" src="{{ field.image_project.url }}">
					<strong style="color:#292c2f;">Projeto</strong>
				</a>
				{% endif %}
			</div>
		</div>

		<div style="display: inline-block; text-align: left; padding: 5px; font-size: 1.2em;  ">
			<div class="module title3">
				<h3 class="module-title">Detalhes</h3>
				<div class="module-content">
							<!--Detalhes-->
							{{ field.particulars }}
				</div>
			</div>
			<br>
		</div>

		<!-- Tela para envio de pergunta ao cliente -->
		<div class="modal fade" id="emailModal_Provider" tabindex="-1" role="dialog" aria-labelledby="emailModal_ProviderLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
				<div class="modal-header">
					<h3 class="modal-title" id="emailModal_ProviderLabel">Dados da Cotação</h3>
						Cotação Nº: {{ field.id }}<br>
						Móvel: 
						{% if field.mobile_type|lower == '_Outro'|lower %}
							{{ field.mobile_description|truncatechars:15 }}
						{% else %}
							{{ field.mobile_type|truncatechars:15 }}
						{% endif %} -
						<strong>{{ field.stage|truncatechars:10 }}</strong>
						<br>
						Cliente: {{ field.client|truncatechars:10 }}
						<br>
				</div>

				<!-- Formulário de envio de email -->
				<div class="modal-body">
					<form enctype="multipart/form-data" method="POST" action="{% url 'qnow_provider:quotation_provider_email_inquire' field.id %}">
						{% csrf_token %}
						<!-- Email do cliente -->
						<div class="form-group" hidden>
							<label for="recipient-name" class="col-form-label">E-mail do cliente:</label>
							<input type="text" class="form-control" name="email_client" id="recipient-name" value="{{ field.client.email }}" readonly=true> 
						</div>

						<!-- Pergunta do marceneiro -->	
						<div class="form-group">
							<label for="message-text" class="col-form-label">Digite aqui suas dúvidas em relação ao projeto.</label>
							<textarea class="form-control" id="message-text" name="inquire_provider" style="height: 15em;"></textarea>
						</div>

						<!-- botões de ações -->	
						<div class="modal-footer">
							<input name="button9" value="Fecha" class="btn btn-default uk-button" type="button" data-dismiss="modal">
							<input name="button9" value="Enviar E-mail" class="btn btn-default uk-button" type="submit">

						</div>
					</form>
				</div>

				</div>
			</div>
			</div>


		{% endfor %}
	</div>

	{% endif %}

</section>

<section class="parallax-section-2">
	<div class="row">
		<div class="col-sm-12 col-md-12" id="parallax2">
			<div class="module ">
				<div class="module-content">
					<div class="uk-text-contrast uk-flex uk-flex-center" data-uk-parallax="{bg: -300}"
						style="min-height: 120px; background-color: rgb(41, 44, 47); background-repeat: no-repeat; background-size: cover; background-position: 50% -42.435px;">
						<div class="container1170" style="padding:15px 15px;">
							<div class="uk-grid">
								<div class="uk-width-medium-3-4">
									<h3 embed-responsive-item style="margin-top pull-left:15px;">
										<h2>{{ user }}</h2>
										Pesqusia aqui todas as cotações disponíveis para serem cotadas pela sua
										MARCENARIAS.
									</h3>
								</div>
								<div class="uk-width-medium-1-4 uk-text-right inverted">
									{% if user.is_authenticated %}
									<a class="uk-button raleway16"
										href="{% url 'qnow_provider:quotation_provider' %}">Voltar à Lista de Cotações</a>
									{% endif %}
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}
{% block footer %}
{% endblock %}