qnow_client/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.conf.urls import handler404,  handler500


app_name = 'qnow_client'

urlpatterns = [
  path('quotation_client/', views.quotation_client ,name='quotation_client'),
  path('quotation_client_list/<int:client_id>', views.quotation_client_list ,name='quotation_client_list'),
  path('quotation_client_edit/<int:quotation_id>', views.quotation_client_edit ,name='quotation_client_edit'),
  path('quotation_client_delete/<int:quotation_id>/<str:action>', views.quotation_client_delete ,name='quotation_client_delete'),
  path('quotation_client_email/', views.quotation_client_email ,name='quotation_client_email'),
  path('quotation_client_approved/<int:quotationprice_id>', views.quotation_client_approved ,name='quotation_client_approved'),
  path('quotation_client_comment/<int:quotation_id>', views.quotation_client_comment ,name='quotation_client_comment'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'qnow_client.views.error_404_view'
handler500 = 'qnow_client.views.error_500_view'

qnow_site/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'qnow_site'

urlpatterns = [
    path('', views.site ,name='site'),
    path('accounts/login/', views.site ,name='site'), 
    path('contact/', views.contact ,name='contact'),
    path('about/', views.about ,name='about'),
    path('blog/', views.blog ,name='blog'),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

""" 
O path accounts/login foi usado, para o acesso ao site principal e não a tela de login.
Isto porque, esta plataforma acessa dois tipos de login, o client e provider, para tal,
foram criadas rotas diferentes. Mas ao recuperar a senha, o link padrão, leva para o 
escrito acima e redirecionei ele para abrir o site 
"""

qnow_user/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView,LogoutView
from . import views


app_name = 'qnow_user'

urlpatterns = [
    path('login_client_start/', views.login_client_start, kwargs={'origin': 'client' }, name='login_client_start'),
    path('login_provider_start/', views.login_provider_start, kwargs={'origin': 'provider' }, name='login_provider_start'),
    
    path('login_client/',   LoginView.as_view(template_name='../templates/login.html',
                                     extra_context={'next':'qnow_client:quotation_client',
                                                    'origin':'client',
                                                    'active_page_client_provider':'active'
                                                    }
                                    ), name="login_client"),
    path('login_provider/', LoginView.as_view(template_name='../templates/login.html',
                                     extra_context={'next':'qnow_provider:quotation_provider',
                                                    'origin':'provider',
                                                    'active_page_client_provider':'active'
                                                    }
                                    ), name="login_provider"),

    path('logout/', LogoutView.as_view(template_name='../templates/index.html',
                                    extra_context={'next_page':'qnow_site:site',
                                                   'active_page_site': 'active',
                                    }),name='logout'),

    path('register_client/', views.register, kwargs={'origin': 'client' }, name='register_client'),
    path('register_provider/', views.register, kwargs={'origin': 'provider' }, name='register_provider'),

]

quotation-now/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
import re
from django.contrib.auth import urls,views


urlpatterns = [
    path('', include('qnow_site.urls',namespace='site')),
    path('admin/', admin.site.urls),
    path('accounts/', include('qnow_user.urls',namespace='accounts')),
    path('client/', include('qnow_client.urls',namespace='client')),
    path('provider/', include('qnow_provider.urls',namespace='provider')),
    path('', include('django.contrib.auth.urls')),
    ]

if settings.DEBUG:
    import debug_toolbar
    from django.urls import include
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls,namespace='debug')),
    ] + urlpatterns


#admin.site.site_header = 'Quotation-NOW'    
#admin.site.index_title = 'Q-NOW(Administrador)'    
#admin.site.site_title = 'Q-NOW'    

admin.site.site_header = 'MGA-Cotações'    
admin.site.index_title = 'MGA(Administrador)'    
admin.site.site_title = 'MGA'    

qnow_client/forms.py
from django import forms
from .models import Quotation, MobilieType, QuotationStage  

class MobileTypeForm(forms.ModelForm):
    class Meta:
        model = MobilieType

        fields = (
            '__all__'
        )

class QuotationStageForm(forms.ModelForm):
    class Meta:
        model = QuotationStage

        fields = (
            '__all__'
        )

class QuotationForm(forms.ModelForm):
    class Meta:
        model = Quotation
        fields = (
            'id',
            'house_type',
            'house_set',
            'mobile_type',
            'mobile_description',
            'particulars',
            'image_environment',
            'image_project'

        )

        labels = {
            'id': 'Nº da Cotação',
            'house_type': 'Como é seu imóvel?',
            'house_set':'Nome do condomínio ou residencial',
            'mobile_type': 'Para qual móvel deseja cotações?',
            'mobile_description':'Para "_Outro", coloque o nome aqui.(Ex: Aparador)',
            'particulars': 'Nos conte como deseja seu móvel, tamanho do ambiente, função e demais detalhes importantes',
            'image_environment':'1º Imagem - Insira aqui uma imagem do ambiente ou do projeto/desenho.',
            'image_project':'2º Imagem - Insira aqui uma imagem do ambiente ou do projeto/desenho.'
        }

        widgets = {
            'house_set': forms.TextInput(
                attrs={'placeholder': 'Nome do condomínio ou residencial'}
                ),
            'mobile_description': forms.TextInput(
                attrs={'placeholder': 'Se a escolha foi "Outro" indique aqui o móvel a ser cotar'}
                ),
            'particulars': forms.Textarea(
                attrs={'cols': 40,'style':'width: 100%; height: 50%; resize: none; !important;',
                    'placeholder': 
                        'Informe aqui, as caracteristicas importantes de como deseja este móvel e as medidas do ambiente em questão. '
                        +'\n\n'+
                        'Se não souber explicar, podemos entrar em contato e lhe ajudar.'+'\n'+
                        'O nosso primeiro contato é pelo whatsapp, com isto, deixe aqui seu nº.'
                    }
                )
        }

qnow_client/views.py
from django.shortcuts import render, redirect, Http404, render_to_response, get_list_or_404, get_object_or_404
from django.template.loader import render_to_string, get_template
from django.utils.safestring import mark_safe
from django.template import Context, RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from datetime import datetime,date,timedelta
from django.core.mail import EmailMessage, BadHeaderError, EmailMultiAlternatives
from django.conf import settings
import uuid
import threading
from .models import Quotation, QuotationStage
from qnow_provider.models import QuotationPrice
from .forms import QuotationForm
from qnow_user.models import User

# Função lambda que retorna um count de Quotation chamada pela def quotation_client
count_quotation = lambda client : Quotation.objects.filter(client_id=client).count()

# Função para o erro 404 - Somente com DEBUG = False 
def error_404_view(request, exception):
    Context = {"message": "Quando uma página não é encontrada, indica que algo deu errado ou que o endereço informado esta incorreto!"}
    return render(request,'../qnow_site/templates/404.html', Context)

# Função para o erro 500 - Somente com DEBUG = False 
def error_500_view(request):
    Context = {"message": "Erro 500 - Desculpe pelo erro!"}
    return render(request,'../qnow_site/templates/500.html', Context)


# Grava a cotação do cliente
@login_required
def quotation_client(request):
    template_name = "../templates/client_quotation.html"

    # Verifica o acesso do provider na opção cliente, força a entrar corretamente
    if request.user.role == 'provider':
        # Messagem de alerta, onde o provider usa o acesso errado a plataforma
        messages.add_message(request, messages.INFO, 'Desculpe, acesso restrito aos clientes!')
        messages.add_message(request, messages.INFO, 'Tente novamente aqui e agora.')

        # Executa logout quanto fora da área de cotação
        logout(request)

        settings.LOGIN_REDIRECT_URL = 'qnow_provider:quotation_provider'
        return redirect('qnow_user:login_provider')

    form = QuotationForm(request.POST or None, request.FILES or None)
    if request.method == "POST":
        if request.user.is_authenticated:
            Quotation = form.save(commit=False)

            # Retorna o stage(estágio) padrão para inclusão 0 = Pendente
            quotationstage = QuotationStage.objects.get(status=0)
            Quotation.stage_id = quotationstage.id

            # Gravando o usuário logado a cotação
            Quotation.client = request.user

            # UUID gerado para o campo slug
            if not Quotation.id:
                Quotation.slug = uuid.uuid4()

            # Gravando e redirecionando para a lista de cotações do usuário
            if form.is_valid():
                form.save(commit=True)

                # Após salvar, enviar um email ao cliente e uma mensagem na tela
                messages.add_message(request, messages.SUCCESS, 'Cotação Nº: '+str(Quotation.id)+' envida com sucesso!')

                t1 = threading.Thread(target=quotation_client_email, args=(Quotation,'cadastrada',settings.SEND_EMAIL_SIS))
                t1.start()
                #quotation_client_email(Quotation,'cadastrada',settings.SEND_EMAIL_SIS)
                if settings.SEND_EMAIL_SIS == True:
                    messages.add_message(request, messages.SUCCESS, 'Um e-mail de confirmação foi enviado pra você. Verifique sua conta de e-mail.')

                return redirect("qnow_client:quotation_client_list", Quotation.client_id)
            else:
                form = QuotationForm()
        else:
            # Se não estiver conectado, redirecionar para tela de login
            context = {"origin": "client", "active_page_client_provider": "active"}
            return redirect("qnow_user:login_client_start")
    else:
        form = QuotationForm()
       
    context = {"active_page_client_provider": "active", "acao": "Enviar", "form": form}
    return render(request, template_name, context)


# Lista as cotações do cliente logado
@login_required #(redirect_field_name='qnow_user:login_provider_start')
def quotation_client_list(request, client_id=0):
    template_name = "../templates/client_quotation_list.html"

    # Verifica se o usuário logado é o mesmo requisitado
    if client_id != request.user.id:
        response = render_to_response('404.html')
        response.status_code = 404
        return response

    # Pesquisa as cotações do usuário logago
    quotation = Quotation.objects.filter(client=client_id,removed=False)

    # Lambda que retorna a quantidade de dados para ser listados
    if quotation.count() > 0:
        message = ''
    else:
        message = str(request.user) + ', você ainda não possui cotações!'


    # Verifica se encontrou e renderiza
    if Quotation.id:
        context = { "active_page_client_provider": "active", 
                    "message": message,
                    "quotation": quotation}
        return render(request, template_name, context)

# Marca qual cotação foi aprovada pelo cliente e envia um email para os interessados
@login_required
def quotation_client_approved(request,quotationprice_id=0):
    if request.POST.get('price_id'):
        # Reprova todos os orçamentos primieiro. Isto garante a aprovação correta quando o client resolver trocar de provider
        QuotationPrice.objects.filter(quotation_number=quotationprice_id).update(approved=False)  

        # Aprova o valor orçado pelo provider 
        quotationprice_update_row = QuotationPrice.objects.filter(pk=request.POST.get('price_id')).update(approved=True,commission_paid_date=datetime.now()+timedelta(days=7),approved_date=datetime.now())  

        # Retorna id para o stage = 4 aprovado
        quotationstage = QuotationStage.objects.get(status=4)

        # Alterando o stage da cotação para 4 = aprovado 
        Quotation.objects.filter(pk=quotationprice_id).update(stage_id=quotationstage.id)

        # Após aprovar, enviar um email ao cliente e a marcenaria e uma mensagem na tela
        messages.add_message(request, messages.INFO, 'Cotação Nº: '+str(quotationprice_id)+' aprovada com sucesso!')

        # Dados para o envio do email

        quotation_email =  Quotation.objects.get(pk=quotationprice_id)

        t4 = threading.Thread(target=quotation_client_email, args=(quotation_email,'aprovada',settings.SEND_EMAIL_SIS))
        t4.start()

        if settings.SEND_EMAIL_SIS == True:
            messages.add_message(request, messages.INFO, 'Verifique sua conta de e-mail.')

    else:
        # 
        messages.add_message(request, messages.INFO, 'Atenção! Para aprovar uma cotação, é preciso marcá-la!')
        messages.add_message(request, messages.INFO, 'Volte a cotação Nº: '+str(quotationprice_id)+' e marque-a!')

    # Incluir melhores testes aqui
    return redirect("qnow_client:quotation_client_list", request.user.id)

@login_required
def quotation_client_edit(request, quotation_id=0):
    template_name = "../templates/client_quotation.html"

    # Localiza a cotação pelo seu id para edição
    quotation = get_object_or_404(Quotation, pk=quotation_id)

    # Verifica se o usuário logado é o mesmo requisitado
    if quotation.client_id != request.user.id:
        raise Http404

    form = QuotationForm(instance=quotation)
    if request.method == "POST":
        if request.user.is_authenticated:
            form = QuotationForm(
                request.POST or None, request.FILES or None, instance=quotation
            )
            if form.is_valid():
                form.save()
     
                # Após salvar, enviar um email ao cliente e uma mensagem na tela
                messages.add_message(request, messages.INFO, 'Cotação Nº: '+str(quotation.id)+' alterada com sucesso!')

                t2 = threading.Thread(target=quotation_client_email, args=(quotation,'alterada',settings.SEND_EMAIL_SIS))
                t2.start()
                #quotation_client_email(quotation,'alterada',settings.SEND_EMAIL_SIS)
                if settings.SEND_EMAIL_SIS == True:
                    messages.add_message(request, messages.INFO, 'Verifique sua conta de e-mail.')

                # Depois de salvo, renderizar pra lista de cotações do usúario
                return redirect("qnow_client:quotation_client_list", quotation.client_id)
        else:
            context = {"origin": "client", "active_page_client_provider": "active"}
            return redirect("qnow_user:login_client_start")
    else:
        context = {
            "active_page_client_provider": "active",
            "acao": "Enviar",
            "form": form,
        }
        return render(request, template_name, context)

def quotation_client_email(request,acao='ERROR',send_email_sis='False'):
    if send_email_sis == True:
        template_name = "../templates/client_email.html"
        
        subject = 'MGA-Cotações - Cotação Nº: '+str(request.id)+' - '+str(request.client)[:10]+'...'
        
        emails_providers = []
        emails_providers.append(settings.EMAIL_HOST_USER)
        
        if acao == 'removida':          # E-mail enviado ao client
            message = 'Sua cotação foi '+acao+' com sucesso!.'
        elif acao == 'aprovada':        # E-mail enviado ao client    
            # Email do provider aprovado - Enviar email avisando
            provider = QuotationPrice.objects.get(quotation_number=request.id,approved=True)  

            # Emails dos providers reprovados - Enviar email avisando
            qprovider_not_approved = QuotationPrice.objects.filter(quotation_number=request.id,approved=False)
            if qprovider_not_approved:            
                emails_providers_not_approved = []
                emails_providers_not_approved.append(settings.EMAIL_HOST_USER)

qnow_client/templates/client_quotation.html
{% extends "default.html" %}
{% load static %}
{% block content %}

<!-- Page Title -->
<section class="page-title">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-12 title">
				<h2>Cotação Agora - {{ user.username }}</h2>
				<ol class="breadcrumb">
					<li>Você esta aqui: &nbsp;</li>
					<li><a class="pathway" href="{% url 'qnow_site:site' %}">Home</a></li>
					<li><a class="pathway" href="#">Acesso à Plataforma</a></li>
					<li><a class="pathway" href="#">Clientes</a></li>
					<li class="active">Cotação Agora</li>
				</ol>
			</div>
		</div>
	</div>
</section>

<section class="main-body">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-12">
				<article itemtype="http://schema.org/Article" itemscope="" class="item item-page">
					<meta content="en-GB" itemprop="inLanguage">
					<div itemprop="articleBody">
						<div class="uk-grid">

 							<div class="uk-width-medium-1-2">
								<label for="text1"><i style="color:#ff0000; vertical-align:top;"></i>
									Seja Bem vindo! {{ user|capfirst }}<br><br>
									Entenda como você facilmente pode fazer um pedido de cotação usando nossa plataforma.
								</label>

								<p class="dropcap">1<strong>Informações Residenciais</strong><br>
									Entender em que tipo de ambiente você mora como por exemplo: casa ou apartamento, 
									nos dando a possobilidade de dimensionar melhor a produção do seu móvel.</p>
								<hr>
								<p class="dropcap">2<strong>Informações do Móvel Planejado</strong><br>
									Nos indique que móvel deseja cotar, e se não estiver na lista escolha a 
									opção "Outro", e digite no próximo campo, o nome deste móvel.</p>
								<hr>
								<p class="dropcap">3<strong>Caracteristica do Móvel Desejado</strong><br>
									No campo seguinte, digite os dados importantes, e 
									inclua: medidas, foto do local e se possuir uma foto do projeto ou planta.
									E se não souber? Entraremos em contato para conversarmos.</p>
								<hr>
								<p class="dropcap">4<strong>Envio da Cotação</strong><br>
									Por fim, clique no botão enviar para cadastrar sua cotação. 
									Tão logo ela chegue em nosso sistema, iremos analisá-la, detalhá-la e liberar 
									para que as marcenarias cadastradas em nossa plataforma faça sua cotação.</p>
								<hr>
							</div>
						<div class="uk-width-medium-1-2">
								<div class="gbs3">
									<form action="#" enctype="multipart/form-data" method="POST" name="quote" id="chronoform-quote" class="chronoform">
								        {% csrf_token %}
								   		{{ form.mon_field_erros }}
										{% for field in form %}
										
  										<div class="form-group" id="form-row-text1">


											<label for="text1" class="control-label required_label">
												{{ field.label_tag }}

												{% if 'ambiente'|upper not in field.label|upper and 'projeto'|upper not in field.label|upper %}	
											    	<i class="fa" style="color:#ff0000; font-size:9px; vertical-align:top;"></i>
												{% endif %}
 											</label>
											<div class="gcore-display-table">
												{{ field }}
												{{ field.errors }}
											</div>
										</div>
											
										{% endfor %}

										 <div class="form-group" id="form-row-button9">
											<div class="gcore-display-table" id="fin-button9">
												<input name="button9" id="button9" value={{ acao }} class="btn btn-default uk-button uk-button-default demo" type="submit">
											</div>
											
											<div>
												<label id=message_quotation_email for="text1" class="control-label required_label">
												</label>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</article>
			</div>
		</div>
	</div>
</section>

{% endblock %}
{% block footer %}
{% endblock %}

qnow_client/templates/client_quotation_delete.html
{% extends "default.html" %}
{% load cloudinary %}
{% load static %}
{% block content %}
<section class="page-title">
	<div class="container">
		<div class="row">
			<div class="col-sm-12 col-md-12 title">
				<h2>Minhas Cotações - {{ user.username }}</h2>
				<ol class="breadcrumb">
					<li>Você esta aqui: &nbsp;</li>
					<li><a class="pathway" href="{% url 'qnow_site:site' %}">Home</a></li>
					<li class="active">Minhas Cotações</li>
				</ol>
			</div>
		</div>
	</div>
</section>

<!-- Cotações do usuário -->
<section>
	{% for field in quotation %}
		<div class="container col-sm-6 col-md-6">
			<div class="row">
				<article itemtype="#" itemscope="" class="item item-page-6">
					<meta content="en-GB" itemprop="inLanguage">
					<div itemprop="articleBody">
						<div class="module title1">
							<h2 class="module-title">{{ field.stage }}</h2>
						</div>


							<!-- Móvel -->
						<strong>
							<h2 class="pe-7s-exapnd2" font="size:10px;"> 
								{% if field.mobile_type|lower == '_Outro'|lower %}
									{{ field.mobile_description }}
								{% else %}
									{{ field.mobile_type }} 
								{% endif %}
								<small>Cotação Nº:{{ field.id }}</small>
							</h2>
						</strong>

						<!-- Imagem do ambiente e projeto-->
						<div data-uk-grid-margin="" class="uk-grid uk-grid-width-medium-1-2 uk-grid-collapse">
							<!-- Imagens do ambiente -->
							<div style="padding: 5px;">
								{% if field.image_environment|lower == 'None'|lower %}
									<a title="Sem foto do ambiente<br>Situação: {{ field.stage }} - Cotação Nº: {{ field.id }}<br><br><br>" data-uk-lightbox="{group:'group1'}" href="{% static '/images/no-image.png' %}">
										<img alt="MGA-Cotações<br>Sem foto do ambiente" src="{% static '/images/no-image.png' %}" height="200px;" width="400px;" class="uk-border-rounded">
										<small>Foto do Ambiente</small>
									</a>
								{% elif field.image_environment|lower != 'None'|lower %}
									<a title="Foto do seu ambiente<br>Situação: {{ field.stage }} - Cotação Nº: {{ field.id }}<br><br><br>" data-uk-lightbox="{group:'group1'}" href="{{ field.image_environment.url }}">
										<img alt="MGA-Cotações<br>Foto do ambiente" src="{{ field.image_environment.url }}" height="200px" width="400px" class="uk-border-rounded">
										<small>Foto do Ambiente</small>
									</a>
								{% endif %}
							</div>

							<!-- Imagens do projeto -->
							<div style="padding: 5px;">
								{% if field.image_project|lower == 'None'|lower %}
									<a title="Sem foto do projeto<br>Situação: {{ field.stage }} - Cotação Nº: {{ field.id }}<br><br><br>"  data-uk-lightbox="{group:'group1'}" href="{% static '/images/no-image.png' %}">
										<img alt="MGA-Cotações<br>Sem foto do projeto" src="{% static '/images/no-image.png' %}" height="200px;" width="400px;" class="uk-border-rounded">
										<small>Foto do Projeto</small>
									</a>
								{% elif field.image_project|lower != 'None'|lower %}
									<a title="Foto do seu projeto<br>Situação: {{ field.stage }} - Cotação Nº: {{ field.id }}<br><br><br>" data-uk-lightbox="{group:'group1'}" href="{{ field.image_project.url }}">
										<img alt="MGA-Cotações<br>Foto do projeto" src="{{ field.image_project.url }}" height="200px;" width="400px;" class="uk-border-rounded">
										<small>Foto do Projeto</small>
									</a>
								{% endif %}
							</div>
						</div>

						<!-- Corpo do card, com as Caracteristicas, situação e edição do projeto,
														tudo respeintando a situação da cotação-->
						<div class="card-body" style="padding: 5px;">
							<!--Tipo do imóvel-->
							<label class="readmore">Imóvel:</label>
							<label class="card-text">{{ field.house_type }}</label>
							<br>
							
						
							<!--Situação -->
							<div class="card">
								<div class="card-header" id="headingTwo">
									<label class="card-title readmore">
										Situação:
									</label>
							
									<label role="button" class="collapsed uk-icon-arrow-circle-down" type="button" data-toggle="collapse"
										data-target="#{{ field.slug }}" aria-expanded="false" aria-controls="collapseTwo aria-controls">
											{{ field.stage }}

									</label>
								</div>

								<div id="{{ field.slug }}" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
									<div class="card-body">
										{{ field.stage.explication }}
									</div>
								</div>
							</div>


							<!--Caracteristicas do móvel-->
							<div class="card">
								<div class="card-header" id="headingTwo">
									<label class="card-title readmore">
										Caracteristicas:
									</label>
						
									<label role="button" class="collapsed uk-icon-arrow-circle-down" type="button" data-toggle="collapse" data-target="#{{ field.id }}"
										aria-expanded="false" aria-controls="collapseTwo aria-controls">
										Veja aqui...
									</label>
								</div>
								<div id="{{ field.id }}" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
									<div class="card-body">
										{{ field.particulars }}
									</div>
								</div>
							</div>
						
							<!-- Botão para editar a cotação -->
							<div class="card-footer text-left">
								<p class="readmore">
									{% if user.is_authenticated %}
										<!--Botão de edição quando stage for "0 Pendente"-->
										{% if 'Pendente'|lower in field.stage|lower %}
											<h3 class="readmore" style="text-align: center">{{ message }}</h3>
											<a itemprop="url" href="{% url 'qnow_client:quotation_client_delete' quotation_id=field.id action='delete'  %}"
												class="btn btn-danger">Sim, remover agora!</a>
										{% endif %}
										<!--Botão para nova cotação-->
										{% if 'client'|lower in user.role|lower %}
											<a itemprop="url" href="{% url 'qnow_client:quotation_client_list' field.client_id  %}" class="btn btn-primary">
												Minhas Cotações(C)</a>
										{% endif %}
									{% endif %}
								</p>
							</div>

						</div>
					</div>
				</article>
			</div>
		</div>
	{% endfor %}
</section>



<section class="parallax-section-2">
	<div class="row">
		<div class="col-sm-12 col-md-12" id="parallax2">
			<div class="module ">
				<div class="module-content">
					<div class="uk-text-contrast uk-flex uk-flex-center" data-uk-parallax="{bg: -300}"
						style="min-height: 160px; background-color: rgb(41, 44, 47); background-repeat: no-repeat; background-size: cover; background-position: 50% -42.435px;">
						<div class="container1170" style="padding:20px 15px;">
							<div class="uk-grid">
								<div class="uk-width-medium-3-4">
									<h3 embed-responsive-item style="margin-top pull-left:15px;">
										<h2>{{ user }}</h2>
										Inicie agora mesmo uma nova cotação e receba das melhores
										MARCENARIAS os melhores preços do mercado.</h3>
								</div>
								<div class="uk-width-medium-1-4 uk-text-right inverted">
									<h3 embed-responsive-item style="margin-top pull-left:5px;">
										{% if user.is_authenticated %}
											<a class="uk-button uk-child-width-expand raleway16" style="font-size: 0.75em;" href="{% url 'qnow_client:quotation_client' %}">Iniciar uma nova cotação</a>
										{% else %}
											<a href="{% url 'qnow_user:login_client_start' %}" class="uk-button uk-child-width-expand raleway16" style="font-size: 0.75em;">Inicie sua cotação aqui!</a>
											
										{% endif %}
									</h3>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}
{% block footer %}
{% endblock %}